{% set name = "mido" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mido-{{ version }}.tar.gz
  sha256: 84282e3ace34bca3f984220db2dbcb98245cfeafb854260c02e000750dca86aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - mido
    - mido.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mido.readthedocs.io/
  summary: MIDI Objects for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Walter-0
    - mxr-conda
